version: '2'
services:
  gateway:
    image: lebabach/microservices-gateway:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
      #- zuul.routes.gamblingproducer.url=http://192.168.1.3:8081
    ports:
      - 8080:8080

